# This message contains high-level motor state information
# 4 angles, represented in radian, for the 4 servos
float32 front_left_angle    #front left angle
float32 rear_left_angle     #rear left angle
float32 rear_right_angle    #rear right angle
float32 front_right_angle   #front right angle

# 4 speed values for the 4 dc motors, normalized between 0 and 1
float32 front_left_speed  #front left speed
float32 rear_left_speed   #rear left speed
float32 rear_right_speed  #rear right speed
float32 front_right_speed #front right speed