# This message contains high-level motor state information
# 4 angles, represented in ticks, for the 4 servos
int16 front_right_angle 	#front right angle
int16 front_left_angle 	#front left angle
int16 rear_left_angle	#rear left angle
int16 rear_right_angle	#rear right angle

# 4 speed values for the 4 dc motors
int16 front_right_speed 	#front right speed
int16 front_left_speed	#front left speed
int16 rear_left_speed	#rear left speed
int16 rear_right_speed	#rear right speed