# Rover Dimension in [m]
rover_length: 0.436
rover_width: 0.475
rover_height: 0.452

wheel_diameter: 0.13677

# Initial Camera Position in [m]
# (Guessed values)
camera_headX: 0.045
camera_headY: 0.0
camera_headZ: 0.030
# Camera Offset from Pitch Axis in [m]
# Stereo Camera (Guessed values)
stereo_cameraO: 0.0
# IR Camera (Guessed values)
ir_cameraO: 0.005

# IMU Position in [m] and Orientation Quaternion
# Central IMU
c_imuX: 0.001
c_imuY: 0.0
c_imuZ: 0.0
#c_imuQX: 0.0
#c_imuQY: 0.0
#c_imuQZ: 0.0
#c_imuQW: 0.001

# Locomotion Control Parameters
# Driving
drive_enc_ppr: 8384                     # Drive encoder pulses per revolution
max_vel: 3.14159265358979323846         # Maximal wheel velocity [rad/s]
# Steering
steer_enc_ppr: 8384                     # Steer encoder pulses per revolution
max_ort: 1.57079632679489661923         # Maximal wheel orientation [rad]

# Elecrical Power Supply Parameters
# Current Sensors
# Set EPS parameters
max_cur_b: 25                           # Maximal current on battery current sensor [A]
max_cur_m: 12                           # Maximal current on motor current sensor [A]
